#
# Copyright 2018 Orkus, Inc
# All Rights Reserved.
#
# @author: Denys Nahurnyi.
# @email:  dnahurnyi@gmail.com
# ---------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: intentmgr
  name: intentmgr-service
spec:
  ports:
  - port: 8096
    protocol: TCP
    targetPort: 8096
    nodePort: 30096
    name: grpc-port
  - port: 8095
    protocol: TCP
    targetPort: 8095
    nodePort: 30095
    name: rest-port
  selector:
    app: intentmgr
  type: NodePort
status:
  loadBalancer: {}
