#
# Copyright 2018 Orkus, Inc
# All Rights Reserved.
#
# @author: Denys Nahurnyi.
# @email:  dnahurnyi@gmail.com
# ---------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: calendar
  name: calendar-service
spec:
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 8088
    nodePort: 30088
    name: grpc-port
  - port: 8087
    protocol: TCP
    targetPort: 8087
    nodePort: 30087
    name: rest-port
  selector:
    app: calendar
  type: NodePort
status:
  loadBalancer: {}
