#
# Copyright 2018 Orkus, Inc
# All Rights Reserved.
#
# @author: Denys Nahurnyi.
# @email:  dnahurnyi@gmail.com
# ---------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: policyreader
  name: policyreader-service
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
    nodePort: 30082
    name: grpc-port
  - port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 30081
    name: rest-port
  selector:
    app: policyreader
  type: NodePort
status:
  loadBalancer: {}
